"""
lesson.py — Lesson dataclass for the self-improvement system.

A Lesson is a single, concrete, reusable insight extracted from a completed
action. Lessons are stored persistently and injected into future planning
prompts when relevant.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Literal

LessonCategory = Literal["planning", "tool_use", "error", "user_preference"]
LessonSource = Literal["llm", "rule"]


@dataclass
class Lesson:
    """A single reusable insight extracted from a completed interaction.

    Attributes:
        id:           Unique identifier (UUID4).
        text:         The lesson itself — concrete and actionable.
        trigger:      Brief description of *when* this lesson applies
                      (used as the similarity-search key for retrieval).
        category:     Broad type: planning, tool_use, error, user_preference.
        confidence:   0.0–1.0 — how confident the engine is this is useful.
        source:       "llm" if written by the LLM; "rule" if generated by the
                      rule-based fallback.
        created_at:   ISO-8601 UTC timestamp of when the lesson was created.
        use_count:    How many times this lesson has been injected into a prompt.
        helpful_count: Times a turn that injected this lesson succeeded.
    """

    text: str
    trigger: str
    category: LessonCategory = "planning"
    confidence: float = 0.7
    source: LessonSource = "llm"
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    created_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    use_count: int = 0
    helpful_count: int = 0

    # ------------------------------------------------------------------
    # Derived helpers
    # ------------------------------------------------------------------

    @property
    def helpfulness(self) -> float:
        """Fraction of uses that led to a successful outcome (0.0 if never used)."""
        return self.helpful_count / self.use_count if self.use_count else 0.0

    @property
    def effective_confidence(self) -> float:
        """Blend of initial confidence and observed helpfulness.

        After 3+ uses, the observed rate starts to dominate.
        """
        if self.use_count < 3:
            return self.confidence
        observed_weight = min(self.use_count / 10, 0.7)
        return (1 - observed_weight) * self.confidence + observed_weight * self.helpfulness

    # ------------------------------------------------------------------
    # Serialisation
    # ------------------------------------------------------------------

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "text": self.text,
            "trigger": self.trigger,
            "category": self.category,
            "confidence": self.confidence,
            "source": self.source,
            "created_at": self.created_at,
            "use_count": self.use_count,
            "helpful_count": self.helpful_count,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "Lesson":
        return cls(
            id=data.get("id", str(uuid.uuid4())),
            text=data["text"],
            trigger=data["trigger"],
            category=data.get("category", "planning"),
            confidence=data.get("confidence", 0.7),
            source=data.get("source", "rule"),
            created_at=data.get("created_at", datetime.now(timezone.utc).isoformat()),
            use_count=data.get("use_count", 0),
            helpful_count=data.get("helpful_count", 0),
        )

    def __repr__(self) -> str:
        return (
            f"Lesson(category={self.category!r}, confidence={self.confidence:.2f}, "
            f'text={self.text[:60]!r}{"..." if len(self.text) > 60 else ""})'
        )
